<?php

namespace Hanafalah\ModuleMedicalProcurement;

use Hanafalah\ModuleMedicalProcurement\Contracts\ModuleMedicalProcurement as ContractsModuleMedicalProcurement;
use Hanafalah\LaravelSupport\Supports\PackageManagement;

class ModuleMedicalProcurement extends PackageManagement implements ContractsModuleMedicalProcurement {}
